###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        container_name: Dayssist_mysql
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=dbname
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=toor
        ports:
            - '8082:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        container_name: Dayssist_webserver
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        container_name: Dayssist_php-fpm
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
